# Generated by Django 5.0.6 on 2024-06-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_service_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='estimated_people',
        ),
        migrations.RemoveField(
            model_name='service',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceType',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='hourlyRate',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ManyToManyField(to='reservation.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ManyToManyField(to='reservation.servicetype'),
        ),
        migrations.CreateModel(
            name='PoolOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.IntegerField(choices=[(1, 'Pool A'), (2, 'Pool B'), (3, 'Pool C'), (4, 'Pool D'), (5, 'Do Not Want To Swim')], default=5)),
                ('attendees', models.IntegerField(default=0)),
                ('special_orders', models.TextField()),
                ('timeslot', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='pool_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.pooloption'),
        ),
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.IntegerField(choices=[(1, 'Room A'), (2, 'Room B'), (3, 'Room C'), (4, 'Room D'), (5, 'Do Not Want a Room')], default=5)),
                ('attendees', models.IntegerField(default=0)),
                ('special_orders', models.TextField()),
                ('timeslot', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservation.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='servicetype',
            name='room_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.roomoption'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ReservationStatus',
        ),
    ]
