# Generated by Django 5.0.6 on 2024-06-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_reservation_estimated_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='timeslot',
            field=models.DateTimeField(),
        ),
    ]
