# Generated by Django 5.0.6 on 2024-06-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_merge_20240606_1539'),
        ('reservation', '0016_merge_20240606_2139'),
    ]

    operations = [
    ]
